//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnoses()
        {
            this.BodyCompositions = new HashSet<BodyCompositions>();
            this.Images = new HashSet<Images>();
            this.Measures = new HashSet<Measures>();
        }
    
        public int IdDiagnosis { get; set; }
        public Nullable<System.DateTime> DiagnosisDate { get; set; }
        public string PhysicalActivity { get; set; }
        public string PhysicalPerception { get; set; }
        public string Feeding { get; set; }
        public string Appetite { get; set; }
        public string WaterConsumption { get; set; }
        public string Dream { get; set; }
        public string StomachUpset { get; set; }
        public string EnergyLevel { get; set; }
        public string StressLevel { get; set; }
        public string SubstanceUse { get; set; }
        public string GeneralComments { get; set; }
        public Nullable<int> IdPatient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyCompositions> BodyCompositions { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measures> Measures { get; set; }
    }
}
