//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInformation
    {
        public int IdGeneralInformation { get; set; }
        public Nullable<int> PhysicalActivity { get; set; }
        public string PhysicalActivityComments { get; set; }
        public string FavoriteFoods { get; set; }
        public string NonFavoriteFoods { get; set; }
        public string DietarySupplements { get; set; }
        public string NutritionalFamiliarity { get; set; }
        public string EatingEmotionalBehavior { get; set; }
        public string GeneralComments { get; set; }
        public Nullable<int> IdPatient { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
