//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitsAndGoals
    {
        public int IdHabitsAndGoals { get; set; }
        public string Caffeine { get; set; }
        public string Alcohol { get; set; }
        public string Cigarette { get; set; }
        public string Drugs { get; set; }
        public string HealthGoals { get; set; }
        public string SpecificNutritionalGoals { get; set; }
        public string Expectations { get; set; }
        public string GeneralComments { get; set; }
        public Nullable<int> IdPatient { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
