//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int IdImage { get; set; }
        public string ImageComments { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<int> IdDiagnosis { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
    }
}
