//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meals
    {
        public int IdMeal { get; set; }
        public string MealType { get; set; }
        public string Equivalences { get; set; }
        public string MealExamples { get; set; }
        public Nullable<int> IdMealPlan { get; set; }
    
        public virtual MealPlans MealPlans { get; set; }
    }
}
