//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalInformation
    {
        public int IdMedicalInformation { get; set; }
        public string ChronicDiseases { get; set; }
        public string HereditaryFamilyHistory { get; set; }
        public string GastrointestinalDiseases { get; set; }
        public string FoodAllergies { get; set; }
        public string NOFoodAllergies { get; set; }
        public string SurgicalHistory { get; set; }
        public string Medications { get; set; }
        public string GeneralMedicalComments { get; set; }
        public Nullable<int> IdPatient { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
