//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDiveneSysServer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthDivineEntities : DbContext
    {
        public HealthDivineEntities()
            : base("name=HealthDivineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<BodyCompositions> BodyCompositions { get; set; }
        public virtual DbSet<Diagnoses> Diagnoses { get; set; }
        public virtual DbSet<GeneralInformation> GeneralInformation { get; set; }
        public virtual DbSet<HabitsAndGoals> HabitsAndGoals { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<MealPlans> MealPlans { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Measures> Measures { get; set; }
        public virtual DbSet<MedicalInformation> MedicalInformation { get; set; }
        public virtual DbSet<Nutritionists> Nutritionists { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
